/**
 * 本文件集中维护项目空间验证阶段的项目列表、全局时间事件流与 D3 决策树模拟数据。
 */
import type { DecisionReplayEvent, DecisionTreeNode, ProjectSpaceSummary } from './types/project-space.type';

/** 左侧项目列表的验证展示数据。 */
export const projectSpaceProjects: ProjectSpaceSummary[] = [
  { id: 'experience-redesign', title: '产品体验升级计划', status: '进行中', decisionCount: 8 },
  { id: 'brand-refresh', title: 'Q3 品牌焕新', status: '进行中', decisionCount: 3 },
  { id: 'mobile-performance', title: '移动端体验优化', status: '进行中', decisionCount: 2 },
  { id: 'community-co-build', title: '社区共建计划', status: '已关闭', decisionCount: 1 },
];

/** 严格按发生时间排序的决策过程事件，不同决策的事件允许互相穿插。 */
export const replayEvents: DecisionReplayEvent[] = [
  {
    id: 'decision-registration',
    sequence: 1,
    phase: '决策',
    timeLabel: '2026-08-03 09:10',
    label: '提出注册路径调整',
    summary: '产品负责人提出缩短注册路径的决策，计划通过两轮提案投票形成结论。',
    actor: '李沐 · 产品负责人',
    evidence: '决策背景与 8 位参与人已记录',
  },
  {
    id: 'registration-proposal-1',
    sequence: 2,
    phase: '提案',
    timeLabel: '2026-08-03 11:00',
    label: '注册提案 A',
    summary: '成员提出保留三步注册，但负责人没有为该提案发起投票。',
    actor: '陈序 · 提案人',
    evidence: '仅创建提案 · 无关联投票轮次',
  },
  {
    id: 'decision-invitation',
    sequence: 3,
    phase: '决策',
    timeLabel: '2026-08-03 15:20',
    label: '提出邀请机制优化',
    summary: '增长负责人提出邀请机制决策，此时注册路径决策仍在推进。',
    actor: '周尧 · 增长负责人',
    evidence: '计划进行 3 轮提案投票',
  },
  {
    id: 'invitation-proposal-1',
    sequence: 4,
    phase: '提案',
    timeLabel: '2026-08-03 17:10',
    label: '邀请提案 A',
    summary: '成员提交邀请码入口前置方案，稍后针对该提案发起投票。',
    actor: '许桐 · 提案人',
    evidence: '提案已创建 · 尚未得出投票结果',
  },
  {
    id: 'vote-invitation-a-rejected',
    sequence: 5,
    phase: '投票',
    timeLabel: '2026-08-04 08:20',
    label: '邀请提案 A 未通过',
    summary: '关联邀请提案 A 的投票轮次关闭，票决结果为拒绝。',
    actor: '投票轮次 #1',
    evidence: '3 赞成 · 6 反对 · 1 弃权',
  },
  {
    id: 'registration-proposal-2',
    sequence: 6,
    phase: '提案',
    timeLabel: '2026-08-04 09:00',
    label: '注册提案 B',
    summary: '成员提出两步式注册，并补充风险账号二次校验。',
    actor: '李沐 · 提案人',
    evidence: '提案已创建 · 等待投票',
  },
  {
    id: 'vote-registration-b-approved',
    sequence: 7,
    phase: '投票',
    timeLabel: '2026-08-04 09:50',
    label: '注册提案 B 通过',
    summary: '关联注册提案 B 的投票轮次关闭，票决结果为通过。',
    actor: '投票轮次 #1',
    evidence: '7 赞成 · 1 反对',
  },
  {
    id: 'decision-onboarding',
    sequence: 8,
    phase: '决策',
    timeLabel: '2026-08-04 10:30',
    label: '提出首访引导改版',
    summary: '在注册决策已有两项提案后，体验团队才提出第三项决策。',
    actor: '陈序 · 体验负责人',
    evidence: '计划进行 4 轮提案投票',
  },
  {
    id: 'decision-privacy-consent',
    sequence: 9,
    phase: '决策',
    timeLabel: '2026-08-04 11:10',
    label: '提出隐私授权方式',
    summary: '法务团队提出隐私授权方式决策，后续可能因外部规则变化终止。',
    actor: '许桐 · 法务负责人',
    evidence: '决策前置条件已记录',
  },
  {
    id: 'onboarding-proposal-1',
    sequence: 10,
    phase: '提案',
    timeLabel: '2026-08-04 13:20',
    label: '首访提案 A',
    summary: '成员提交全屏功能说明方案，随后进入投票。',
    actor: '周尧 · 提案人',
    evidence: '提案已创建 · 尚未得出投票结果',
  },
  {
    id: 'vote-onboarding-a-rejected',
    sequence: 11,
    phase: '投票',
    timeLabel: '2026-08-04 14:10',
    label: '首访提案 A 未通过',
    summary: '关联首访提案 A 的投票轮次关闭，票决结果为拒绝。',
    actor: '投票轮次 #1',
    evidence: '2 赞成 · 7 反对',
  },
  {
    id: 'invitation-proposal-2',
    sequence: 12,
    phase: '提案',
    timeLabel: '2026-08-04 15:30',
    label: '邀请提案 B',
    summary: '成员提交注册后展示邀请入口的方案，但没有发起投票。',
    actor: '周尧 · 提案人',
    evidence: '仅创建提案 · 无关联投票轮次',
  },
  {
    id: 'abandoned-privacy-consent',
    sequence: 13,
    phase: '废弃',
    timeLabel: '2026-08-05 08:40',
    label: '废弃隐私授权决策',
    summary: '因新的统一授权规范生效，该决策失去继续推进的必要。',
    actor: '法务负责人确认',
    evidence: '废弃原因与当时上下文已归档',
  },
  {
    id: 'resolution-registration',
    sequence: 14,
    phase: '决议',
    timeLabel: '2026-08-05 10:00',
    label: '形成注册路径决议',
    summary: '注册路径决策正式采用两步式注册与风险账号二次校验。',
    actor: '决策主持人确认',
    evidence: '第 2 轮提案成为正式决议',
  },
  {
    id: 'onboarding-proposal-2',
    sequence: 15,
    phase: '提案',
    timeLabel: '2026-08-05 11:15',
    label: '首访提案 B',
    summary: '成员提交三步蒙层引导方案，该方案没有进入投票。',
    actor: '陈序 · 提案人',
    evidence: '仅创建提案 · 无关联投票轮次',
  },
  {
    id: 'invitation-proposal-3',
    sequence: 16,
    phase: '提案',
    timeLabel: '2026-08-05 14:00',
    label: '邀请提案 C',
    summary: '成员提交注册后邀请卡片与双向权益方案。',
    actor: '李沐 · 提案人',
    evidence: '提案已创建 · 等待投票',
  },
  {
    id: 'vote-invitation-c-approved',
    sequence: 17,
    phase: '投票',
    timeLabel: '2026-08-05 15:00',
    label: '邀请提案 C 通过',
    summary: '关联邀请提案 C 的投票轮次关闭，票决结果为通过。',
    actor: '投票轮次 #2',
    evidence: '8 赞成 · 2 反对',
  },
  {
    id: 'onboarding-proposal-3',
    sequence: 18,
    phase: '提案',
    timeLabel: '2026-08-06 09:20',
    label: '首访提案 C',
    summary: '成员提交按功能触发提示方案，随后进入投票。',
    actor: '许桐 · 提案人',
    evidence: '提案已创建 · 尚未得出投票结果',
  },
  {
    id: 'vote-onboarding-c-rejected',
    sequence: 19,
    phase: '投票',
    timeLabel: '2026-08-06 10:00',
    label: '首访提案 C 未通过',
    summary: '投票虽获得多数赞成，但未达到三分之二通过条件。',
    actor: '投票轮次 #2',
    evidence: '6 赞成 · 3 反对 · 未达门槛',
  },
  {
    id: 'resolution-invitation',
    sequence: 20,
    phase: '决议',
    timeLabel: '2026-08-06 11:00',
    label: '形成邀请机制决议',
    summary: '邀请机制决策正式采用注册后邀请卡片与双向权益。',
    actor: '决策主持人确认',
    evidence: '第 3 轮提案成为正式决议',
  },
  {
    id: 'onboarding-proposal-4',
    sequence: 21,
    phase: '提案',
    timeLabel: '2026-08-06 15:10',
    label: '首访提案 D',
    summary: '成员提交按需提示与帮助中心入口组合方案。',
    actor: '陈序 · 提案人',
    evidence: '提案已创建 · 等待投票',
  },
  {
    id: 'vote-onboarding-d-approved',
    sequence: 22,
    phase: '投票',
    timeLabel: '2026-08-06 16:00',
    label: '首访提案 D 通过',
    summary: '关联首访提案 D 的投票轮次关闭，票决结果为通过。',
    actor: '投票轮次 #3',
    evidence: '8 赞成 · 1 反对',
  },
  {
    id: 'resolution-onboarding',
    sequence: 23,
    phase: '决议',
    timeLabel: '2026-08-07 10:00',
    label: '形成首访引导决议',
    summary: '首访引导决策正式采用按需功能提示与统一帮助入口。',
    actor: '决策主持人确认',
    evidence: '第 4 轮提案成为正式决议',
  },
  {
    id: 'decision-release-scope',
    sequence: 24,
    phase: '决策',
    timeLabel: '2026-08-07 11:00',
    label: '提出首发范围确认',
    summary: '发布负责人提出首发功能范围决策，用于覆盖更多提案和投票终态。',
    actor: '林川 · 发布负责人',
    evidence: '决策进入提案阶段',
  },
  {
    id: 'release-proposal-cancelled',
    sequence: 25,
    phase: '提案',
    timeLabel: '2026-08-07 11:30',
    label: '提交全量发布提案',
    summary: '成员提交全量发布方案，随后因依赖未就绪主动取消。',
    actor: '林川 · 提案人',
    evidence: '提案已创建 · 尚未投票',
  },
  {
    id: 'cancel-release-proposal',
    sequence: 26,
    phase: '废弃',
    timeLabel: '2026-08-07 11:45',
    label: '取消全量发布提案',
    summary: '提案人在投票前取消方案，该提案不属于投票拒绝。',
    actor: '林川 · 提案人',
    evidence: 'ProposalStatus.CANCELLED',
  },
  {
    id: 'release-proposal-tied',
    sequence: 27,
    phase: '提案',
    timeLabel: '2026-08-07 12:00',
    label: '提交双端同步发布提案',
    summary: '成员提交 Web 与 App 同步发布方案并发起投票。',
    actor: '周尧 · 提案人',
    evidence: '提案进入投票',
  },
  {
    id: 'vote-release-tied',
    sequence: 28,
    phase: '投票',
    timeLabel: '2026-08-07 12:30',
    label: '同步发布投票平票',
    summary: '投票轮次关闭，赞成与反对票相同，提案未通过。',
    actor: '投票轮次 #1',
    evidence: '5 赞成 · 5 反对 · TIED',
  },
  {
    id: 'release-proposal-quorum',
    sequence: 29,
    phase: '提案',
    timeLabel: '2026-08-07 13:00',
    label: '提交邀请制灰度提案',
    summary: '成员提交邀请制灰度方案并设置最低有效票数。',
    actor: '许桐 · 提案人',
    evidence: '法定人数要求 8 人',
  },
  {
    id: 'vote-release-quorum-failed',
    sequence: 30,
    phase: '投票',
    timeLabel: '2026-08-07 13:30',
    label: '灰度投票未达法定人数',
    summary: '投票轮次关闭，实际选票不足法定人数，提案未通过。',
    actor: '投票轮次 #2',
    evidence: '5 人投票 · 要求 8 人 · QUORUM_NOT_MET',
  },
  {
    id: 'release-proposal-vote-cancelled',
    sequence: 31,
    phase: '提案',
    timeLabel: '2026-08-07 14:00',
    label: '提交分批发布提案',
    summary: '成员提交按部门分批发布方案并开启投票。',
    actor: '陈序 · 提案人',
    evidence: '投票轮次已开放',
  },
  {
    id: 'vote-release-cancelled',
    sequence: 32,
    phase: '废弃',
    timeLabel: '2026-08-07 14:20',
    label: '取消分批发布投票',
    summary: '投票开放后发现选项配置错误，本轮投票被取消，不判定提案被拒绝。',
    actor: '决策负责人',
    evidence: 'VoteRoundStatus.CANCELLED',
  },
  {
    id: 'release-proposal-approved',
    sequence: 33,
    phase: '提案',
    timeLabel: '2026-08-07 15:00',
    label: '提交小流量灰度提案',
    summary: '成员提交先向 10% 用户灰度开放的方案。',
    actor: '李沐 · 提案人',
    evidence: '提案进入投票',
  },
  {
    id: 'vote-release-approved',
    sequence: 34,
    phase: '投票',
    timeLabel: '2026-08-07 15:30',
    label: '小流量灰度投票通过',
    summary: '投票轮次关闭，小流量灰度方案达到通过条件。',
    actor: '投票轮次 #4',
    evidence: '9 赞成 · 1 反对 · APPROVED',
  },
  {
    id: 'resolution-release-scope',
    sequence: 35,
    phase: '决议',
    timeLabel: '2026-08-07 16:00',
    label: '形成首发范围决议',
    summary: '依据已关闭投票轮次，正式采用 10% 用户灰度发布。',
    actor: '决策主持人确认',
    evidence: '同时关联 sourceProposalId 与 sourceVoteRoundId',
  },
  {
    id: 'decision-brand-copy',
    sequence: 36,
    phase: '决策',
    timeLabel: '2026-08-08 09:00',
    label: '提出品牌文案确认',
    summary: '品牌负责人提出登录页文案决策，团队已在线下形成明确共识。',
    actor: '苏禾 · 品牌负责人',
    evidence: '决策无需投票',
  },
  {
    id: 'brand-copy-proposal',
    sequence: 37,
    phase: '提案',
    timeLabel: '2026-08-08 10:00',
    label: '提交登录页文案提案',
    summary: '成员提交已形成共识的品牌文案，没有创建投票轮次。',
    actor: '苏禾 · 提案人',
    evidence: '无关联投票轮次',
  },
  {
    id: 'resolution-brand-copy',
    sequence: 38,
    phase: '决议',
    timeLabel: '2026-08-08 11:00',
    label: '直接采纳文案提案',
    summary: '负责人直接采纳开放提案形成正式决议，不提供来源投票轮次。',
    actor: '决策主持人确认',
    evidence: '有 sourceProposalId · 无 sourceVoteRoundId',
  },
  {
    id: 'decision-emergency-fallback',
    sequence: 39,
    phase: '决策',
    timeLabel: '2026-08-08 14:00',
    label: '提出紧急降级策略',
    summary: '负责人针对突发风险提出紧急降级决策。',
    actor: '技术负责人',
    evidence: '无需提案与投票',
  },
  {
    id: 'resolution-emergency-fallback',
    sequence: 40,
    phase: '决议',
    timeLabel: '2026-08-08 14:30',
    label: '直接形成降级决议',
    summary: '负责人直接确认降级结论，决议不关联来源提案和投票轮次。',
    actor: '决策主持人确认',
    evidence: '无 sourceProposalId · 无 sourceVoteRoundId',
  },
  {
    id: 'decision-resolution-lifecycle',
    sequence: 41,
    phase: '决策',
    timeLabel: '2026-08-09 09:00',
    label: '提出灰度策略演进决策',
    summary: '负责人创建一项需要先临时落地、再逐步收口的灰度策略决策。',
    actor: '林川 · 决策负责人',
    evidence: 'DecisionStatus.DISCUSSING',
  },
  {
    id: 'lifecycle-proposal-manually-rejected',
    sequence: 42,
    phase: '提案',
    timeLabel: '2026-08-09 09:20',
    label: '提交全员开放提案',
    summary: '成员提交全员开放方案，但负责人确认其超出当前风险边界，没有创建投票轮次。',
    actor: '周宁 · 提案人',
    evidence: '提案已创建 · 无关联投票轮次',
  },
  {
    id: 'reject-lifecycle-proposal-manually',
    sequence: 43,
    phase: '废弃',
    timeLabel: '2026-08-09 09:40',
    label: '人工拒绝全员开放提案',
    summary: '负责人直接关闭未投票提案；它不是投票拒绝，因此保持灰色废弃状态而不是红色。',
    actor: '林川 · 决策负责人',
    evidence: 'ProposalStatus.REJECTED · 无 VoteRound',
  },
  {
    id: 'resolution-lifecycle-interim',
    sequence: 44,
    phase: '决议',
    timeLabel: '2026-08-09 10:00',
    label: '形成临时灰度决议',
    summary: '先形成仅对内部成员开放的临时决议，为后续正式决议保留替代空间。',
    actor: '决策主持人确认',
    evidence: 'ResolutionKind.INTERIM · ACTIVE',
  },
  {
    id: 'resolution-lifecycle-final',
    sequence: 45,
    phase: '决议',
    timeLabel: '2026-08-09 14:00',
    label: '正式决议替代临时决议',
    summary: '风险条件满足后形成正式决议，原临时决议被标记为已替代。',
    actor: '决策主持人确认',
    evidence: 'FINAL · 原决议 SUPERSEDED',
  },
  {
    id: 'resolution-lifecycle-supplement',
    sequence: 46,
    phase: '决议',
    timeLabel: '2026-08-10 09:00',
    label: '新增灰度例外补充决议',
    summary: '在正式决议上新增一条例外规则，补充决议暂时生效。',
    actor: '决策主持人确认',
    evidence: 'ResolutionKind.SUPPLEMENT · ACTIVE',
  },
  {
    id: 'revoke-resolution-lifecycle-supplement',
    sequence: 47,
    phase: '决议',
    timeLabel: '2026-08-10 11:00',
    label: '撤销灰度例外补充决议',
    summary: '例外条件不再成立，补充决议被撤销；正式决议继续保持有效。',
    actor: '决策主持人确认',
    evidence: 'ResolutionStatus.REVOKED',
  },
];

/** 中部 D3 树形画布使用的项目决策结构。 */
export const decisionReplayTree: DecisionTreeNode = {
  id: 'project-experience-upgrade',
  type: 'project',
  title: '产品体验升级计划',
  subtitle: '项目根节点 · 8 项决策',
  routeStatus: 'neutral',
  children: [
    {
      id: 'decision-registration',
      type: 'decision',
      title: '注册路径调整',
      subtitle: '2026-08-03 09:10 · 2 轮投票',
      routeStatus: 'resolved',
      completionEventId: 'resolution-registration',
      children: [
        { id: 'registration-proposal-1', type: 'proposal', title: '提案 A', subtitle: '2026-08-03 11:00 · 未发起投票', routeStatus: 'unvoted' },
        {
          id: 'registration-proposal-2',
          type: 'proposal',
          title: '提案 B',
          subtitle: '2026-08-04 09:00 · 7 票赞成',
          routeStatus: 'resolved',
          detailEventId: 'vote-registration-b-approved',
          completionEventId: 'resolution-registration',
          children: [
            { id: 'resolution-registration', type: 'resolution', title: '正式决议', subtitle: '2026-08-05 10:00 · 两步式注册', routeStatus: 'resolved', completionEventId: 'resolution-registration' },
          ],
        },
      ],
    },
    {
      id: 'decision-invitation',
      type: 'decision',
      title: '邀请机制优化',
      subtitle: '2026-08-03 15:20 · 3 轮投票',
      routeStatus: 'resolved',
      completionEventId: 'resolution-invitation',
      children: [
        { id: 'invitation-proposal-1', type: 'proposal', title: '提案 A', subtitle: '2026-08-04 08:20 · 投票拒绝', routeStatus: 'rejected', statusEventId: 'vote-invitation-a-rejected' },
        { id: 'invitation-proposal-2', type: 'proposal', title: '提案 B', subtitle: '2026-08-04 15:30 · 未发起投票', routeStatus: 'unvoted' },
        {
          id: 'invitation-proposal-3',
          type: 'proposal',
          title: '提案 C',
          subtitle: '2026-08-05 14:00 · 8 票赞成',
          routeStatus: 'resolved',
          detailEventId: 'vote-invitation-c-approved',
          completionEventId: 'resolution-invitation',
          children: [
            { id: 'resolution-invitation', type: 'resolution', title: '正式决议', subtitle: '2026-08-06 11:00 · 双向权益', routeStatus: 'resolved', completionEventId: 'resolution-invitation' },
          ],
        },
      ],
    },
    {
      id: 'decision-onboarding',
      type: 'decision',
      title: '首访引导改版',
      subtitle: '2026-08-04 10:30 · 4 轮投票',
      routeStatus: 'resolved',
      completionEventId: 'resolution-onboarding',
      children: [
        { id: 'onboarding-proposal-1', type: 'proposal', title: '提案 A', subtitle: '2026-08-04 14:10 · 投票拒绝', routeStatus: 'rejected', statusEventId: 'vote-onboarding-a-rejected' },
        { id: 'onboarding-proposal-2', type: 'proposal', title: '提案 B', subtitle: '2026-08-05 11:15 · 未发起投票', routeStatus: 'unvoted' },
        { id: 'onboarding-proposal-3', type: 'proposal', title: '提案 C', subtitle: '2026-08-06 10:00 · 投票拒绝', routeStatus: 'rejected', statusEventId: 'vote-onboarding-c-rejected' },
        {
          id: 'onboarding-proposal-4',
          type: 'proposal',
          title: '提案 D',
          subtitle: '2026-08-06 15:10 · 8 票赞成',
          routeStatus: 'resolved',
          detailEventId: 'vote-onboarding-d-approved',
          completionEventId: 'resolution-onboarding',
          children: [
            { id: 'resolution-onboarding', type: 'resolution', title: '正式决议', subtitle: '2026-08-07 10:00 · 按需提示', routeStatus: 'resolved', completionEventId: 'resolution-onboarding' },
          ],
        },
      ],
    },
    {
      id: 'decision-privacy-consent',
      type: 'decision',
      title: '隐私授权方式',
      subtitle: '2026-08-04 11:10 · 后续废弃',
      routeStatus: 'abandoned',
      completionEventId: 'abandoned-privacy-consent',
      children: [
        {
          id: 'abandoned-privacy-consent',
          type: 'abandoned',
          title: '决策已废弃',
          subtitle: '2026-08-05 08:40 · 规则变化',
          routeStatus: 'abandoned',
          completionEventId: 'abandoned-privacy-consent',
        },
      ],
    },
    {
      id: 'decision-release-scope',
      type: 'decision',
      title: '首发范围确认',
      subtitle: '覆盖异常投票结果',
      routeStatus: 'resolved',
      completionEventId: 'resolution-release-scope',
      children: [
        {
          id: 'release-proposal-cancelled',
          type: 'proposal',
          title: '全量发布',
          subtitle: '投票前人工取消',
          routeStatus: 'abandoned',
          completionEventId: 'cancel-release-proposal',
        },
        {
          id: 'release-proposal-tied',
          type: 'proposal',
          title: '双端同步发布',
          subtitle: '投票平票 · 未通过',
          routeStatus: 'rejected',
          statusEventId: 'vote-release-tied',
        },
        {
          id: 'release-proposal-quorum',
          type: 'proposal',
          title: '邀请制灰度',
          subtitle: '未达法定人数',
          routeStatus: 'rejected',
          statusEventId: 'vote-release-quorum-failed',
        },
        {
          id: 'release-proposal-vote-cancelled',
          type: 'proposal',
          title: '分批发布',
          subtitle: '投票轮次取消',
          routeStatus: 'abandoned',
          completionEventId: 'vote-release-cancelled',
        },
        {
          id: 'release-proposal-approved',
          type: 'proposal',
          title: '小流量灰度',
          subtitle: '投票通过',
          routeStatus: 'resolved',
          detailEventId: 'vote-release-approved',
          completionEventId: 'resolution-release-scope',
          children: [
            {
              id: 'resolution-release-scope',
              type: 'resolution',
              title: '正式决议',
              subtitle: '10% 用户灰度发布',
              routeStatus: 'resolved',
              completionEventId: 'resolution-release-scope',
            },
          ],
        },
      ],
    },
    {
      id: 'decision-brand-copy',
      type: 'decision',
      title: '品牌文案确认',
      subtitle: '采纳提案但不投票',
      routeStatus: 'resolved',
      completionEventId: 'resolution-brand-copy',
      children: [
        {
          id: 'brand-copy-proposal',
          type: 'proposal',
          title: '登录页文案',
          subtitle: '无投票 · 直接采纳',
          routeStatus: 'resolved',
          completionEventId: 'resolution-brand-copy',
          children: [
            {
              id: 'resolution-brand-copy',
              type: 'resolution',
              title: '正式决议',
              subtitle: '来源提案 · 无来源投票',
              routeStatus: 'resolved',
              completionEventId: 'resolution-brand-copy',
            },
          ],
        },
      ],
    },
    {
      id: 'decision-emergency-fallback',
      type: 'decision',
      title: '紧急降级策略',
      subtitle: '无提案 · 无投票',
      routeStatus: 'resolved',
      completionEventId: 'resolution-emergency-fallback',
      children: [
        {
          id: 'resolution-emergency-fallback',
          type: 'resolution',
          title: '直接决议',
          subtitle: '直接确认结论',
          routeStatus: 'resolved',
          completionEventId: 'resolution-emergency-fallback',
        },
      ],
    },
    {
      id: 'decision-resolution-lifecycle',
      type: 'decision',
      title: '灰度策略演进',
      subtitle: '临时 · 正式 · 补充决议',
      routeStatus: 'resolved',
      completionEventId: 'resolution-lifecycle-final',
      children: [
        {
          id: 'lifecycle-proposal-manually-rejected',
          type: 'proposal',
          title: '全员开放',
          subtitle: '未投票 · 人工拒绝',
          routeStatus: 'abandoned',
          completionEventId: 'reject-lifecycle-proposal-manually',
        },
        {
          id: 'resolution-lifecycle-interim',
          type: 'resolution',
          title: '临时决议',
          subtitle: '后续被正式决议替代',
          routeStatus: 'superseded',
          completionEventId: 'resolution-lifecycle-interim',
          statusEventId: 'resolution-lifecycle-final',
        },
        {
          id: 'resolution-lifecycle-final',
          type: 'resolution',
          title: '正式决议',
          subtitle: '当前持续有效',
          routeStatus: 'resolved',
          completionEventId: 'resolution-lifecycle-final',
        },
        {
          id: 'resolution-lifecycle-supplement',
          type: 'resolution',
          title: '补充决议',
          subtitle: '后续被撤销',
          routeStatus: 'revoked',
          completionEventId: 'resolution-lifecycle-supplement',
          statusEventId: 'revoke-resolution-lifecycle-supplement',
        },
      ],
    },
  ],
};
