/**
 * 本文件定义所有 HTTP API 共享的成功与失败响应契约。
 */

/** 所有成功响应使用的稳定业务码。 */
export const API_SUCCESS_CODE = 'COMMON.OK' as const;

/** 服务端可返回的稳定错误业务码目录。 */
export const API_ERROR_CODES = {
  COMMON_INTERNAL_ERROR: 'COMMON.INTERNAL_ERROR',
  COMMON_VALIDATION_FAILED: 'COMMON.VALIDATION_FAILED',
  COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
  AUTH_UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  AUTH_SESSION_EXPIRED: 'AUTH.SESSION_EXPIRED',
  AUTH_ACCOUNT_UNAVAILABLE: 'AUTH.ACCOUNT_UNAVAILABLE',
  ACCESS_PERMISSION_DENIED: 'ACCESS.PERMISSION_DENIED',
  ACCESS_DATA_SCOPE_DENIED: 'ACCESS.DATA_SCOPE_DENIED',
  ACCESS_SYSTEM_ROLE_PROTECTED: 'ACCESS.SYSTEM_ROLE_PROTECTED',
  ACCESS_LAST_SUPER_ADMIN_REQUIRED: 'ACCESS.LAST_SUPER_ADMIN_REQUIRED',
  ACCESS_GRANT_EXCEEDS_ACTOR: 'ACCESS.GRANT_EXCEEDS_ACTOR',
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT.NOT_FOUND',
  DEPARTMENT_CODE_CONFLICT: 'DEPARTMENT.CODE_CONFLICT',
  DEPARTMENT_INVALID_PARENT: 'DEPARTMENT.INVALID_PARENT',
  DEPARTMENT_CYCLE_DETECTED: 'DEPARTMENT.CYCLE_DETECTED',
  DEPARTMENT_DISABLED: 'DEPARTMENT.DISABLED',
  PROJECT_NOT_FOUND: 'PROJECT.NOT_FOUND',
  PROJECT_READ_ONLY: 'PROJECT.READ_ONLY',
  PROJECT_INVALID_STATUS_TRANSITION: 'PROJECT.INVALID_STATUS_TRANSITION',
  PROJECT_MEMBER_NOT_FOUND: 'PROJECT.MEMBER_NOT_FOUND',
  PROJECT_MEMBER_ALREADY_EXISTS: 'PROJECT.MEMBER_ALREADY_EXISTS',
  PROJECT_MEMBER_CHANGE_NOT_ALLOWED: 'PROJECT.MEMBER_CHANGE_NOT_ALLOWED',
  PROJECT_OWNER_PROTECTED: 'PROJECT.OWNER_PROTECTED',
  DISCUSSION_AREA_NOT_FOUND: 'DISCUSSION_AREA.NOT_FOUND',
  DISCUSSION_AREA_READ_ONLY: 'DISCUSSION_AREA.READ_ONLY',
  DISCUSSION_AREA_PUBLIC_PROTECTED: 'DISCUSSION_AREA.PUBLIC_PROTECTED',
  DISCUSSION_AREA_MEMBER_NOT_FOUND: 'DISCUSSION_AREA.MEMBER_NOT_FOUND',
  DISCUSSION_AREA_MEMBER_ALREADY_EXISTS: 'DISCUSSION_AREA.MEMBER_ALREADY_EXISTS',
  DISCUSSION_AREA_MEMBER_INVALID: 'DISCUSSION_AREA.MEMBER_INVALID',
  PROJECT_CHAT_SEND_NOT_ALLOWED: 'PROJECT.CHAT_SEND_NOT_ALLOWED',
  PROJECT_CHAT_MESSAGE_NOT_FOUND: 'PROJECT.CHAT_MESSAGE_NOT_FOUND',
  PROJECT_CHAT_IDEMPOTENCY_CONFLICT: 'PROJECT.CHAT_IDEMPOTENCY_CONFLICT',
  PROJECT_AUDIT_PRIVATE_TARGET_REQUIRED: 'PROJECT_AUDIT.PRIVATE_TARGET_REQUIRED',
  DECISION_NOT_FOUND: 'DECISION.NOT_FOUND',
  DECISION_AREA_INVALID: 'DECISION.AREA_INVALID',
  DECISION_INVALID_STATUS_TRANSITION: 'DECISION.INVALID_STATUS_TRANSITION',
  DECISION_PARTICIPANT_USER_NOT_FOUND: 'DECISION.PARTICIPANT_USER_NOT_FOUND',
  DECISION_PARTICIPANT_ALREADY_EXISTS: 'DECISION.PARTICIPANT_ALREADY_EXISTS',
  DECISION_PARTICIPANT_CHANGE_NOT_ALLOWED: 'DECISION.PARTICIPANT_CHANGE_NOT_ALLOWED',
  DECISION_CHAT_SEND_NOT_ALLOWED: 'DECISION.CHAT_SEND_NOT_ALLOWED',
  DECISION_CHAT_READ_ONLY: 'DECISION.CHAT_READ_ONLY',
  DECISION_CHAT_MESSAGE_NOT_FOUND: 'DECISION.CHAT_MESSAGE_NOT_FOUND',
  DECISION_CHAT_IDEMPOTENCY_CONFLICT: 'DECISION.CHAT_IDEMPOTENCY_CONFLICT',
  DECISION_PROPOSAL_CHANGE_NOT_ALLOWED: 'DECISION.PROPOSAL_CHANGE_NOT_ALLOWED',
  DECISION_PROPOSAL_NOT_FOUND: 'DECISION.PROPOSAL_NOT_FOUND',
  DECISION_VOTE_ROUND_NOT_FOUND: 'DECISION.VOTE_ROUND_NOT_FOUND',
  DECISION_VOTE_ROUND_CHANGE_NOT_ALLOWED: 'DECISION.VOTE_ROUND_CHANGE_NOT_ALLOWED',
  DECISION_VOTE_ROUND_ALREADY_OPEN: 'DECISION.VOTE_ROUND_ALREADY_OPEN',
  DECISION_VOTER_NOT_ELIGIBLE: 'DECISION.VOTER_NOT_ELIGIBLE',
  DECISION_BALLOT_ALREADY_SUBMITTED: 'DECISION.BALLOT_ALREADY_SUBMITTED',
  DECISION_VOTE_OPTION_INVALID: 'DECISION.VOTE_OPTION_INVALID',
  DECISION_RESOLUTION_CHANGE_NOT_ALLOWED: 'DECISION.RESOLUTION_CHANGE_NOT_ALLOWED',
  DECISION_RESOLUTION_SOURCE_INVALID: 'DECISION.RESOLUTION_SOURCE_INVALID',
  MEETING_NOT_FOUND: 'MEETING.NOT_FOUND',
  MEETING_CREATE_NOT_ALLOWED: 'MEETING.CREATE_NOT_ALLOWED',
  MEETING_LIVE_CONFLICT: 'MEETING.LIVE_CONFLICT',
  MEETING_INVALID_STATUS_TRANSITION: 'MEETING.INVALID_STATUS_TRANSITION',
  MEETING_PARTICIPANT_INVALID: 'MEETING.PARTICIPANT_INVALID',
  MEETING_DECISION_INVALID: 'MEETING.DECISION_INVALID',
  MEETING_LIVEKIT_NOT_CONFIGURED: 'MEETING.LIVEKIT_NOT_CONFIGURED',
  MEETING_LIVEKIT_ROOM_QUERY_FAILED: 'MEETING.LIVEKIT_ROOM_QUERY_FAILED',
  MEETING_LIVEKIT_ROOM_CLOSE_FAILED: 'MEETING.LIVEKIT_ROOM_CLOSE_FAILED',
  MEETING_CALL_EXPIRED: 'MEETING.CALL_EXPIRED',
  MEETING_ENTRY_NOT_OPEN: 'MEETING.ENTRY_NOT_OPEN',
  MEETING_PRIVATE_DECISION_PARTICIPANTS_INCOMPLETE: 'MEETING.PRIVATE_DECISION_PARTICIPANTS_INCOMPLETE',
  AI_MODEL_CONFIGURATION_INVALID: 'AI.MODEL_CONFIGURATION_INVALID',
  AI_MODEL_AUTHENTICATION_FAILED: 'AI.MODEL_AUTHENTICATION_FAILED',
  AI_MODEL_BUDGET_EXCEEDED: 'AI.MODEL_BUDGET_EXCEEDED',
  AI_MODEL_RATE_LIMITED: 'AI.MODEL_RATE_LIMITED',
  AI_MODEL_NOT_FOUND: 'AI.MODEL_NOT_FOUND',
  AI_MODEL_TIMEOUT: 'AI.MODEL_TIMEOUT',
  AI_MODEL_CANCELLED: 'AI.MODEL_CANCELLED',
  AI_MODEL_UNAVAILABLE: 'AI.MODEL_UNAVAILABLE',
  AI_MODEL_RESPONSE_INVALID: 'AI.MODEL_RESPONSE_INVALID',
  AI_MODEL_REQUEST_FAILED: 'AI.MODEL_REQUEST_FAILED',
  AI_THREAD_NOT_FOUND: 'AI.THREAD_NOT_FOUND',
  AI_THREAD_RUN_ACTIVE: 'AI.THREAD_RUN_ACTIVE',
  AI_THREAD_PINNED_LIMIT_EXCEEDED: 'AI.THREAD_PINNED_LIMIT_EXCEEDED',
  AI_THREAD_CURSOR_INVALID: 'AI.THREAD_CURSOR_INVALID',
  AI_RUN_NOT_FOUND: 'AI.RUN_NOT_FOUND',
  AI_RUN_INVALID_STATUS_TRANSITION: 'AI.RUN_INVALID_STATUS_TRANSITION',
  AI_MESSAGE_INVALID_DISPATCH_TRANSITION: 'AI.MESSAGE_INVALID_DISPATCH_TRANSITION',
  AI_RUN_NOT_RETRYABLE: 'AI.RUN_NOT_RETRYABLE',
  AI_IDEMPOTENCY_CONFLICT: 'AI.IDEMPOTENCY_CONFLICT',
  AI_EXECUTION_LEASE_INVALID: 'AI.EXECUTION_LEASE_INVALID',
  AI_EXECUTION_LEASE_EXPIRED: 'AI.EXECUTION_LEASE_EXPIRED',
  AI_EVENT_SEQUENCE_CONFLICT: 'AI.EVENT_SEQUENCE_CONFLICT',
  AI_TOOL_NOT_REGISTERED: 'AI.TOOL_NOT_REGISTERED',
  AI_TOOL_INPUT_INVALID: 'AI.TOOL_INPUT_INVALID',
  AI_TOOL_TARGET_NOT_DISCOVERED: 'AI.TOOL_TARGET_NOT_DISCOVERED',
  AI_TOOL_EXECUTION_FAILED: 'AI.TOOL_EXECUTION_FAILED',
  AI_RUNTIME_SERVICE_UNAUTHORIZED: 'AI.RUNTIME_SERVICE_UNAUTHORIZED',
  RESOURCE_CONFLICT: 'RESOURCE.CONFLICT',
} as const;

/** 由错误码目录派生的稳定错误业务码联合类型。 */
export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

/** 请求参数或字段校验失败时返回的一条明细。 */
export type ApiErrorDetail = {
  /** 出错字段的路径；非字段级错误时可以省略。 */
  field?: string;
  /** 面向用户展示的中文错误说明。 */
  message: string;
  /** 触发错误的稳定校验规则名称。 */
  rule?: string;
};

/** API 成功响应。 */
export type ApiSuccessResponse<T> = {
  /** 标识本次请求成功，供调用方执行联合类型收窄。 */
  success: true;
  /** 所有成功响应统一使用的稳定业务码。 */
  code: typeof API_SUCCESS_CODE;
  /** 面向用户展示的中文结果说明。 */
  message: string;
  /** 接口返回的真实业务数据。 */
  data: T;
  /** 服务端生成响应时的 Unix 毫秒时间戳。 */
  timestamp: number;
  /** 贯穿服务端日志与本次响应的请求标识。 */
  requestId: string;
};

/** API 失败响应。 */
export type ApiErrorResponse = {
  /** 标识本次请求失败，供调用方执行联合类型收窄。 */
  success: false;
  /** 调用方可以稳定判断的字符串错误业务码。 */
  code: ApiErrorCode;
  /** 面向用户展示且不泄露内部实现的中文错误说明。 */
  message: string;
  /** 失败响应不携带业务数据，始终为 `null`。 */
  data: null;
  /** 参数或字段级错误明细；没有明细时省略。 */
  details?: ApiErrorDetail[];
  /** 服务端生成响应时的 Unix 毫秒时间戳。 */
  timestamp: number;
  /** 贯穿服务端日志与本次响应的请求标识。 */
  requestId: string;
  /** 产生错误的请求路径。 */
  path: string;
};

/** API 响应的可判别联合，调用方应通过 `success` 判断成功或失败。 */
export type ApiResponse<T> = ApiSuccessResponse<T> | ApiErrorResponse;
