/**
 * 本文件定义所有 HTTP API 共享的成功与失败响应契约。
 */

/** 所有成功响应使用的稳定业务码。 */
export const API_SUCCESS_CODE = 'COMMON.OK' as const;

/** 服务端可返回的稳定错误业务码目录。 */
export const API_ERROR_CODES = {
  COMMON_INTERNAL_ERROR: 'COMMON.INTERNAL_ERROR',
  COMMON_VALIDATION_FAILED: 'COMMON.VALIDATION_FAILED',
  COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
  AUTH_UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  AUTH_SESSION_EXPIRED: 'AUTH.SESSION_EXPIRED',
  AUTH_ACCOUNT_UNAVAILABLE: 'AUTH.ACCOUNT_UNAVAILABLE',
  ACCESS_PERMISSION_DENIED: 'ACCESS.PERMISSION_DENIED',
  ACCESS_DATA_SCOPE_DENIED: 'ACCESS.DATA_SCOPE_DENIED',
  ACCESS_SYSTEM_ROLE_PROTECTED: 'ACCESS.SYSTEM_ROLE_PROTECTED',
  ACCESS_LAST_SUPER_ADMIN_REQUIRED: 'ACCESS.LAST_SUPER_ADMIN_REQUIRED',
  ACCESS_GRANT_EXCEEDS_ACTOR: 'ACCESS.GRANT_EXCEEDS_ACTOR',
  DEPARTMENT_NOT_FOUND: 'DEPARTMENT.NOT_FOUND',
  DEPARTMENT_CODE_CONFLICT: 'DEPARTMENT.CODE_CONFLICT',
  DEPARTMENT_INVALID_PARENT: 'DEPARTMENT.INVALID_PARENT',
  DEPARTMENT_CYCLE_DETECTED: 'DEPARTMENT.CYCLE_DETECTED',
  DEPARTMENT_DISABLED: 'DEPARTMENT.DISABLED',
  MATTER_NOT_FOUND: 'MATTER.NOT_FOUND',
  MATTER_READ_ONLY: 'MATTER.READ_ONLY',
  MATTER_INVALID_STATUS_TRANSITION: 'MATTER.INVALID_STATUS_TRANSITION',
  MATTER_MEMBER_NOT_FOUND: 'MATTER.MEMBER_NOT_FOUND',
  MATTER_MEMBER_ALREADY_EXISTS: 'MATTER.MEMBER_ALREADY_EXISTS',
  MATTER_MEMBER_CHANGE_NOT_ALLOWED: 'MATTER.MEMBER_CHANGE_NOT_ALLOWED',
  MATTER_OWNER_PROTECTED: 'MATTER.OWNER_PROTECTED',
  DISCUSSION_AREA_NOT_FOUND: 'DISCUSSION_AREA.NOT_FOUND',
  DISCUSSION_AREA_READ_ONLY: 'DISCUSSION_AREA.READ_ONLY',
  DISCUSSION_AREA_PUBLIC_PROTECTED: 'DISCUSSION_AREA.PUBLIC_PROTECTED',
  DISCUSSION_AREA_MEMBER_NOT_FOUND: 'DISCUSSION_AREA.MEMBER_NOT_FOUND',
  DISCUSSION_AREA_MEMBER_ALREADY_EXISTS: 'DISCUSSION_AREA.MEMBER_ALREADY_EXISTS',
  DISCUSSION_AREA_MEMBER_INVALID: 'DISCUSSION_AREA.MEMBER_INVALID',
  MATTER_CHAT_SEND_NOT_ALLOWED: 'MATTER.CHAT_SEND_NOT_ALLOWED',
  MATTER_CHAT_MESSAGE_NOT_FOUND: 'MATTER.CHAT_MESSAGE_NOT_FOUND',
  MATTER_CHAT_IDEMPOTENCY_CONFLICT: 'MATTER.CHAT_IDEMPOTENCY_CONFLICT',
  MATTER_AUDIT_PRIVATE_TARGET_REQUIRED: 'MATTER_AUDIT.PRIVATE_TARGET_REQUIRED',
  DECISION_NOT_FOUND: 'DECISION.NOT_FOUND',
  DECISION_AREA_INVALID: 'DECISION.AREA_INVALID',
  DECISION_INVALID_STATUS_TRANSITION: 'DECISION.INVALID_STATUS_TRANSITION',
  DECISION_PARTICIPANT_USER_NOT_FOUND: 'DECISION.PARTICIPANT_USER_NOT_FOUND',
  DECISION_PARTICIPANT_ALREADY_EXISTS: 'DECISION.PARTICIPANT_ALREADY_EXISTS',
  DECISION_PARTICIPANT_CHANGE_NOT_ALLOWED: 'DECISION.PARTICIPANT_CHANGE_NOT_ALLOWED',
  DECISION_CHAT_SEND_NOT_ALLOWED: 'DECISION.CHAT_SEND_NOT_ALLOWED',
  DECISION_CHAT_READ_ONLY: 'DECISION.CHAT_READ_ONLY',
  DECISION_CHAT_MESSAGE_NOT_FOUND: 'DECISION.CHAT_MESSAGE_NOT_FOUND',
  DECISION_CHAT_IDEMPOTENCY_CONFLICT: 'DECISION.CHAT_IDEMPOTENCY_CONFLICT',
  DECISION_PROPOSAL_CHANGE_NOT_ALLOWED: 'DECISION.PROPOSAL_CHANGE_NOT_ALLOWED',
  DECISION_PROPOSAL_NOT_FOUND: 'DECISION.PROPOSAL_NOT_FOUND',
  DECISION_VOTE_ROUND_NOT_FOUND: 'DECISION.VOTE_ROUND_NOT_FOUND',
  DECISION_VOTE_ROUND_CHANGE_NOT_ALLOWED: 'DECISION.VOTE_ROUND_CHANGE_NOT_ALLOWED',
  DECISION_VOTE_ROUND_ALREADY_OPEN: 'DECISION.VOTE_ROUND_ALREADY_OPEN',
  DECISION_VOTER_NOT_ELIGIBLE: 'DECISION.VOTER_NOT_ELIGIBLE',
  DECISION_BALLOT_ALREADY_SUBMITTED: 'DECISION.BALLOT_ALREADY_SUBMITTED',
  DECISION_VOTE_OPTION_INVALID: 'DECISION.VOTE_OPTION_INVALID',
  DECISION_RESOLUTION_CHANGE_NOT_ALLOWED: 'DECISION.RESOLUTION_CHANGE_NOT_ALLOWED',
  DECISION_RESOLUTION_SOURCE_INVALID: 'DECISION.RESOLUTION_SOURCE_INVALID',
  MEETING_NOT_FOUND: 'MEETING.NOT_FOUND',
  MEETING_CREATE_NOT_ALLOWED: 'MEETING.CREATE_NOT_ALLOWED',
  MEETING_LIVE_CONFLICT: 'MEETING.LIVE_CONFLICT',
  MEETING_INVALID_STATUS_TRANSITION: 'MEETING.INVALID_STATUS_TRANSITION',
  MEETING_PARTICIPANT_INVALID: 'MEETING.PARTICIPANT_INVALID',
  MEETING_DECISION_INVALID: 'MEETING.DECISION_INVALID',
  MEETING_LIVEKIT_NOT_CONFIGURED: 'MEETING.LIVEKIT_NOT_CONFIGURED',
  MEETING_LIVEKIT_ROOM_CLOSE_FAILED: 'MEETING.LIVEKIT_ROOM_CLOSE_FAILED',
  MEETING_PRIVATE_DECISION_PARTICIPANTS_INCOMPLETE: 'MEETING.PRIVATE_DECISION_PARTICIPANTS_INCOMPLETE',
  RESOURCE_CONFLICT: 'RESOURCE.CONFLICT',
} as const;

/** 由错误码目录派生的稳定错误业务码联合类型。 */
export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];

/** 请求参数或字段校验失败时返回的一条明细。 */
export type ApiErrorDetail = {
  /** 出错字段的路径；非字段级错误时可以省略。 */
  field?: string;
  /** 面向用户展示的中文错误说明。 */
  message: string;
  /** 触发错误的稳定校验规则名称。 */
  rule?: string;
};

/** API 成功响应。 */
export type ApiSuccessResponse<T> = {
  /** 标识本次请求成功，供调用方执行联合类型收窄。 */
  success: true;
  /** 所有成功响应统一使用的稳定业务码。 */
  code: typeof API_SUCCESS_CODE;
  /** 面向用户展示的中文结果说明。 */
  message: string;
  /** 接口返回的真实业务数据。 */
  data: T;
  /** 服务端生成响应时的 Unix 毫秒时间戳。 */
  timestamp: number;
  /** 贯穿服务端日志与本次响应的请求标识。 */
  requestId: string;
};

/** API 失败响应。 */
export type ApiErrorResponse = {
  /** 标识本次请求失败，供调用方执行联合类型收窄。 */
  success: false;
  /** 调用方可以稳定判断的字符串错误业务码。 */
  code: ApiErrorCode;
  /** 面向用户展示且不泄露内部实现的中文错误说明。 */
  message: string;
  /** 失败响应不携带业务数据，始终为 `null`。 */
  data: null;
  /** 参数或字段级错误明细；没有明细时省略。 */
  details?: ApiErrorDetail[];
  /** 服务端生成响应时的 Unix 毫秒时间戳。 */
  timestamp: number;
  /** 贯穿服务端日志与本次响应的请求标识。 */
  requestId: string;
  /** 产生错误的请求路径。 */
  path: string;
};

/** API 响应的可判别联合，调用方应通过 `success` 判断成功或失败。 */
export type ApiResponse<T> = ApiSuccessResponse<T> | ApiErrorResponse;
